[package]
name = "j_toll"
version = "0.1.0"
authors = ["Joel Zand√©n <info@joelzanden.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
